#!/bin/sh

set -e

lb config noauto \
	--architectures i386 \
	--linux-flavours 686-pae \
	--archive-areas "main contrib non-free" \
	--apt-source-archives false \
	--backports true \
	--debian-installer netinst \
	--memtest memtest86+ \
	--bootappend-live "boot=live config quiet splash persistence \
	keyboard-variants=euro \
	locales=nl_NL.UTF-8,en_US.UTF-8" \
	"${@}"
