#!/bin/sh

set -e

lb config noauto \
	--architectures i386 \
	--linux-flavours 686-pae \
	--archive-areas "main contrib non-free" \
	--apt-source-archives false \
	--backports true \
	--bootappend-live "boot=live config quiet splash persistence" \
	"${@}"
