#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2013 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Kde_services ()
{
	# Checking if package is installed or already configured
	if [ ! -e /usr/share/kde4 ] || \
	   [ -e /var/lib/live/config/kde-services ]
	then
		return
	fi

	echo -n " kde-services"

	# Reading kernel command line
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.keyboard-layouts=*|keyboard-layouts=*)
				LIVE_KEYBOARD_LAYOUTS="${_PARAMETER#*keyboard-layouts=}"
				;;

			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done

	Configure_kde_services
}

Configure_kde_services ()
{
	# Enabling keyboard selector
	if echo "${LIVE_KEYBOARD_LAYOUTS}" | grep -qs ','
	then
		if [ ! -e "/home/${LIVE_USERNAME}/.kde/share/config/kxkbrc" ]
		then
			mkdir -p "/home/${LIVE_USERNAME}/.kde/share/config/"

cat > "/home/${LIVE_USERNAME}/.kde/share/config/kxkbrc" << EOF
[Layout]
DisplayNames=${LIVE_KEYBOARD_LAYOUTS}
IndicatorOnly=false
LayoutList=${LIVE_KEYBOARD_LAYOUTS}
ShowFlag=false
SwitchMode=Global
Use=true
EOF

			chown ${LIVE_USERNAME}:${LIVE_USERNAME} "/home/${LIVE_USERNAME}/.kde" -R
		fi
	fi

	# Disabling unnecessary KDE services
	sudo -u "${LIVE_USERNAME}" kwriteconfig --file kres-migratorrc --group Migration --key Enabled --type bool false
	kwriteconfig --file /usr/share/kde4/services/kded/freespacenotifier.desktop --group "Desktop Entry" --key X-KDE-Kded-autoload --type bool false

	# should enable kxkb in ~/.kde/share/config/kxkbrc
	# if multiple layouts are specified. gnome does it per default.

	# Creating state file
	touch /var/lib/live/config/kde-services
}

Kde_services

